# Site settings
title: Khang Le
email: khang.n.le552@gmail.com
description: Sharing parts of my life to the Internet
baseurl: ""
url: ""

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
